spring:
  datasource:
    url: jdbc:mysql://localhost:3306/webshop_rest_prod?useSSL=false
    username: webshop_prod_user
    password: password
  jpa:
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    database: mysql